# Generated by Django 5.2.5 on 2025-08-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_user_posts_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='users',
        ),
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default='users', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
